### PR TITLE
enable link insertion shortcut

### PR DESCRIPTION
**Pull request by wowthedoge**
Made it so that Ctrl+B adds the needed asterisks and places the cursor between them, so no need to highlight text before bolding them. Same for italics.

Tests: I have only tested locally, without Cypress (I have not set up the testing yet).

### CODE REVIEW

**Comment by wowthedoge** [comment]
Just a small change I wanted to do to test the waters as my first contribution to open source 😅. This was my own idea, please don't hesitate to let me know if this isn't the intended behavior.

**Comment by AdrianoFerrari** [comment]
Hi. Thanks for the submission!

I think that similar to this change, but more immediately useful, would be to add a "turn italic text into Markdown link" feature.

Basically, doing almost exactly what this Github comment window does. Here's how I imagine it would work:
1. User selects some text and presses "Ctrl+Shift+K" (instead of "Ctrl+K", which is taken for "Split card down").
2. selected text gets wrapped in square brackets, followed by `(url)`, like this: `[selected text here](url)`

(Bonus: if the selected text *is* a URL, then use it in the `(url)` section, so user would end up with : `[link text](https://the.url.they.selected)`)

What do you think?

**Comment by wowthedoge** [comment]
Yeah, sounds good! I'll try my hand at that.

**Comment by wowthedoge** [comment]
Hey, here's the feature suggested. I noticed `ctrl+shift+k` wass already taken for 'merge card up', like an undo for `ctrl+k`. This can also be done with `ctrl+shift+up` so I've went ahead and replaced `ctrl+shift+k` with the insert markdown link functionality you mentioned. For consistency, I've also removed `ctrl+shift+j` as an undo for `ctrl+j`. What do you think?

**Comment by wowthedoge** [comment]
Ok! Here it is, "mod+shift+j/k" restored and the insert link changed to be using "mod+alt+k".

**Comment by AdrianoFerrari** [comment]
Merged, and added to the "Shortcut" menus.

Thanks for implementing this!

**Comment by wowthedoge** [comment]
That's great! Thank you for the opportunity. If there's any other features you need help with, I'll be glad to contribute!

**Pull request merged**
